### ISSUE TITLE
Apply Clean Architecture

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#58]

**Comment by aidanmrli** [comment]
Aidan Wed 16 Nov: Have separate folder for entities, use case interactors, and controllers (routing). 

Possibly make a data persistence layer (data access layer) for database logic. Idea: isolate upper layers from specific db technology. if we change the db, only need to change files in this layer.
(prev comment from TAs: You have your DAO in the same place as your controller - separate these two)

Questions to ask: 

Q1. Do we need input/output boundary or can we access the use case interactor from the controller?

Q2. is user.save() fine in use case interactor? (technically, save is interacting with the db directly. On the other hand, our entities are Mongoose Schema, and save is an abstraction provided by Mongoose, so save is technically from the entities)

**Comment by BerkeAltiparmak** [comment]
Current approach:
Controllers -> Use Case Interactors -> Controller/Presenter
Need to confirm if we need this approach instead:
DAO -> Controllers -> Input Boundary -> Use Case Interactors -> Output Boundary -> Controller/Presenter -> DAO

Overall we did a great job this week in having a cleaner architecture. Let's go guys!

**Comment by aidanmrli** [comment]
Observer pattern addeventlistener in the controller. setinputboundary, setoutputboundary in the controller

**Comment by aidanmrli** [comment]
Comments after Thurs 17 Nov TLI session: we do not necessarily need input/output boundary as the endpoints in the controllers are literally the input/output boundaries.

We should add comments to the entities schema file - technically, because we are so reliant on MongoDB and the mongoose schema wrapper, this isn't clean. However, because this is a MERN app, it is focused on MongoDB. Ideally, we would create an abstract class or something for an entity and implement the class in Mongo in a data persistence layer, possibly not even using Mongoose schema. However, this is too much work and it's not feasible given the scope of our project (need to alter every file in the backend).

**Comment by aidanmrli** [comment]
**Feedback after Milestone 4:**
- Project adheres to clean architecture for the most part, although transcript should be an entity as well

There are some challenges storing a Mongoose schema inside a Mongoose schema. Since our Transcript already follows a consistent data format, and we have a regulated data structure representing each transcript, we think that it is potentially not worth revamping our whole project at this stage. Our Transcript representation (while not an explicit entity) is an object that has very consistent attributes (the raw file, and the intents), and so we believe it is scalable.
