### ISSUE TITLE
Click Bubbles to open Modal

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#62]

**Comment by BerkeAltiparmak** [comment]
The logic:
The user clicks a bubble.
The intent that is on that bubble is identified.
The intent's name, frequency, and associated are retrieved from the id of the bubble (the bubble's id stores all these info in a string).
Presenting these pieces of information on a React Modal.

Things to improve:
The associates of aggregated bubbles (multiple transcripts) is not 100% accurate, need to work at the backend to fix that.
The modal appears at the left bottom of the screen, which is not ideal for a modal. This problem is due to the way we designed the Dashboard (frontend), need to collaborate together to identify what is causing this and then I can solve it.
The id of the nodes (bubbles) store all of the information. We can decide if this is ideal or not together.

**Comment by aidanmrli** [comment]
This was completed successfully 18 days prior to 5 Dec 2022.
